name: MinecraftPracticePlugin
version: '1.0-SNAPSHOT'
main: net.crusadergames.minecraft.plugins.practice.MinecraftPracticePlugin
api-version: '1.21.1'
authors: [ Jerry Balderas ]
description: This is a sample Minecraft plugin for Spigot 1.21.1
website: https://crusadergames.net

commands:
  tendies:
    description: "Eating tendies with my favorite spicy sauce."
    usage: "/tendies"
